/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package Paneles;

import Entidades.Perro;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.LinkedList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;


public class PanelPrincipal extends java.awt.Frame {

    /**
     * Creates new form PanelPrincipal
     */
    String rutaLogo = "src/img/logo.png";
    String userNamePlaceHolder = "👤 Username";
    String cedulaPlaceHolder = "🔑 Clave, Cédula o DNI";
    DogsPanel panelPerros = new DogsPanel();
    LinkedList<Perro> listadoPerros = new LinkedList();
    
    public PanelPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        agregarImagen(logos, rutaLogo);
        agregarPlaceholder(userNameInput, userNamePlaceHolder);
        agregarPlaceholder(cedulaInput, cedulaPlaceHolder);
        System.out.println(fondoFormulario.getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPrincipal = new javax.swing.JPanel();
        fondoFormulario = new javax.swing.JPanel();
        tituloLogin = new javax.swing.JLabel();
        userNameInput = new javax.swing.JTextField();
        cedulaInput = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        datosIncorrectosMensaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logos = new javax.swing.JLabel();
        nombreEmpresa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(728, 396));
        setMinimumSize(new java.awt.Dimension(728, 396));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoPrincipal.setBackground(new java.awt.Color(48, 27, 82));
        fondoPrincipal.setMaximumSize(new java.awt.Dimension(728, 396));
        fondoPrincipal.setPreferredSize(new java.awt.Dimension(728, 396));

        fondoFormulario.setBackground(new java.awt.Color(243, 243, 243));
        fondoFormulario.setBounds(430, (fondoFormulario.getWidth() - fondoPrincipal.getWidth() ) / 2, 240, 235);
        fondoFormulario.setPreferredSize(new java.awt.Dimension(240, 236));
        fondoFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloLogin.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        tituloLogin.setForeground(new java.awt.Color(48, 27, 82));
        tituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLogin.setText("BIENVENIDO");
        fondoFormulario.add(tituloLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, -1));

        userNameInput.setBackground(new java.awt.Color(245, 245, 245));
        userNameInput.setForeground(new java.awt.Color(171, 170, 170));
        userNameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameInput.setText("Username");
        userNameInput.setToolTipText("");
        userNameInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        userNameInput.setMaximumSize(new java.awt.Dimension(200, 30));
        userNameInput.setMinimumSize(new java.awt.Dimension(200, 30));
        userNameInput.setName(""); // NOI18N
        userNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameInputActionPerformed(evt);
            }
        });
        fondoFormulario.add(userNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 68, 200, 30));

        cedulaInput.setBackground(new java.awt.Color(245, 245, 245));
        cedulaInput.setForeground(new java.awt.Color(171, 170, 170));
        cedulaInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cedulaInput.setText(" Cédula o DNI");
        cedulaInput.setToolTipText("");
        cedulaInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        fondoFormulario.add(cedulaInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 30));

        loginButton.setBackground(new java.awt.Color(48, 27, 82));
        loginButton.setForeground(new java.awt.Color(245, 245, 245));
        loginButton.setText("Ingresar");
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(48, 27, 82), 1, true));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        fondoFormulario.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 185, 90, 25));

        signUpButton.setBackground(new java.awt.Color(48, 27, 82));
        signUpButton.setForeground(new java.awt.Color(245, 245, 245));
        signUpButton.setText("Registro");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        fondoFormulario.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 185, 90, 25));

        datosIncorrectosMensaje.setForeground(new java.awt.Color(255, 51, 51));
        datosIncorrectosMensaje.setText("Usuario o contraseña incorrecto");
        datosIncorrectosMensaje.setVisible(false);
        fondoFormulario.add(datosIncorrectosMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, -1));

        jPanel1.setBackground(new java.awt.Color(48, 27, 82));
        jPanel1.setPreferredSize(new java.awt.Dimension(236, 236));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logos.setToolTipText("");
        logos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(logos, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 10, 120, 120));

        nombreEmpresa.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        nombreEmpresa.setForeground(new java.awt.Color(245, 245, 245));
        nombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEmpresa.setText("Paw Patrols");
        jPanel1.add(nombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 140, 150, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adopta uno, \nllévalo en su cajita");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 180, 230, 30));

        javax.swing.GroupLayout fondoPrincipalLayout = new javax.swing.GroupLayout(fondoPrincipal);
        fondoPrincipal.setLayout(fondoPrincipalLayout);
        fondoPrincipalLayout.setHorizontalGroup(
            fondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPrincipalLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(fondoFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fondoPrincipalLayout.setVerticalGroup(
            fondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPrincipalLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(fondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fondoFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(fondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 728, 396));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm


    private void userNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameInputActionPerformed

    }

    private void agregarPlaceholder(JTextField component, String text) {
        final String placeholder = text;
        component.setText(placeholder);
        component.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (component.getText().equals(placeholder)) {
                    component.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (component.getText().isEmpty()) {
                    component.setText(placeholder);
                }
            }
        });

    }//GEN-LAST:event_userNameInputActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void mostrarPanel(JPanel p) {

        p.setSize(fondoPrincipal.getWidth(), fondoPrincipal.getHeight());
        p.setLocation(0, 0);
        fondoPrincipal.removeAll();
        fondoPrincipal.add(p, BorderLayout.CENTER);
        fondoPrincipal.revalidate();
        fondoPrincipal.repaint();

    }

    
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        if (userNameInput.getText().equalsIgnoreCase(userNamePlaceHolder) && cedulaInput.getText().equalsIgnoreCase(cedulaPlaceHolder)) {

        } else if (userNameInput.getText().equalsIgnoreCase("Juanderpablo") && cedulaInput.getText().equalsIgnoreCase("27492044-0")) {
            datosIncorrectosMensaje.setVisible(false);
            System.out.println("Biendevido Juanderpablo");
            agregarPlaceholder(userNameInput, userNamePlaceHolder);
            agregarPlaceholder(cedulaInput, cedulaPlaceHolder);
            mostrarPanel(panelPerros);

        } else {
            System.out.println("Clave incorrecta, vuelve a intentarlo");

            datosIncorrectosMensaje.setVisible(true);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    public static void agregarImagen(JLabel component, String root) {

        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(component.getWidth(), component.getHeight(), Image.SCALE_DEFAULT));
        component.setIcon(icon);
        component.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulaInput;
    private javax.swing.JLabel datosIncorrectosMensaje;
    private javax.swing.JPanel fondoFormulario;
    private javax.swing.JPanel fondoPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logos;
    private javax.swing.JLabel nombreEmpresa;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel tituloLogin;
    private javax.swing.JTextField userNameInput;
    // End of variables declaration//GEN-END:variables

}
